### ISSUE TITLE
proxy setting  for download WMTS element in python program

### ISSUE THREAD

**Issue by khannaum** [ioam/geoviews#46]
Kindly guide where to set the proxy setting in python program to load WMTS element,

**NoteBook:**
windows 64bit
SET http_proxy="proxy address"
SET https_proxy="proxy adress"
jupyter notebook
on notebook WMTS load easily it works fine

but it does not load WMTS elements directly from same python program
windows 64bit
SET http_proxy="proxy address"
SET https_proxy="proxy adress"

python my_program.py
raise SkipRendering("No valid tile source URL found in WMTS "

SkipRendering: No valid tile source URL found in WMTS Element, rendering skipped.

**Comment by jbednar** [comment]
I'm not sure how one would go about setting that up. I don't think this issue is specific to GeoViews, as it would presumably apply to Bokeh as well, and it depends on the specific mechanism by which Bokeh calls out to an internet address. You could try running the Bokeh WMTS example and if you have a similar issue, asking about that on the Bokeh mailing list.

**Comment by khannaum** [comment]
Thanks for the tip/help . I will try from that.
